import type { Metadata } from "next";
import "../styles/globals.css";
import StoreProvider from "@/store/provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-100 p-3">
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
